CREATE EXTERNAL TABLE IF NOT EXISTS {dbname}.{tablename} (
  `identity_lineitemid` string,
  `identity_timeinterval` string,
  `bill_invoiceid` string,
  `bill_billingentity` string,
  `bill_billtype` string,
  `bill_payeraccountid` string,
  `bill_billingperiodstartdate` string,
  `bill_billingperiodenddate` string,
  `lineitem_usageaccountid` string,
  `lineitem_lineitemtype` string,
  `lineitem_usagestartdate` string,
  `lineitem_usageenddate` string,
  `lineitem_productcode` string,
  `lineitem_usagetype` string,
  `lineitem_operation` string,
  `lineitem_availabilityzone` string,
  `lineitem_resourceid` string,
  `lineitem_usageamount` string,
  `lineitem_normalizationfactor` string,
  `lineitem_normalizedusageamount` string,
  `lineitem_currencycode` string,
  `lineitem_unblendedrate` string,
  `lineitem_unblendedcost` string,
  `lineitem_blendedrate` string,
  `lineitem_blendedcost` string,
  `lineitem_lineitemdescription` string,
  `lineitem_taxtype` string,
  `product_productname` string,
  `product_availability` string,
  `product_availabilityzone` string,
  `product_clockspeed` string,
  --`product_currentgeneration` string,
  `product_computefamily` string,
  `product_computetype` string,
  `product_currentgeneration` string,
  --`product_databaseengine` string,
  `product_dedicatedebsthroughput` string,
  --`product_deploymentoption` string,
  `product_description` string,
  `product_durability` string,
  --`product_ecu` string,
  `product_edition` string,
  --`product_endpointtype` string,
  --`product_enginecode` string,
  `product_enhancednetworkingsupported` string,
  --`product_freequerytypes` string,
  `product_fromlocation` string,
  `product_fromlocationtype` string,
  `product_group` string,
  `product_groupdescription` string,
  `product_inputmode` string,
  `product_instancefamily` string,
  `product_instancetype` string,
  --`product_licensemodel` string,
  `product_location` string,
  `product_locationtype` string,
  `product_maxiopsburstperformance` string,
  `product_maxiopsvolume` string,
  `product_maxthroughputvolume` string,
  `product_maxvolumesize` string,
  `product_memory` string,
  --`product_memorygib` string,
  --`product_messagedeliveryfrequency` string,
  --`product_messagedeliveryorder` string,
  --`product_minvolumesize` string,
  `product_networkperformance` string,
  `product_operatingsystem` string,
  `product_operation` string,
  `product_outputmode` string,
  `product_physicalprocessor` string,
  --`product_preinstalledsw` string,
  `product_processorarchitecture` string,
  `product_processorfeatures` string,
  `product_productfamily` string,
  --`product_queuetype` string,
  `product_requestdescription` string,
  `product_requesttype` string,
  `product_resourceendpoint` string,
  `product_routingtarget` string,
  `product_routingtype` string,
  `product_servicecode` string,
  `product_sku` string,
  `product_storage` string,
  `product_storageclass` string,
  `product_storagemedia` string,
  `product_storagetype` string,
  `product_subscriptiontype` string,
  --`product_tenancy` string,
  `product_supportedmodes` string,
  `product_tolocation` string,
  `product_tolocationtype` string,
  `product_transfertype` string,
  `product_usagetype` string,
  `product_vcpu` string,
  --`product_vcpu2` string,
  `product_version` string,
  `product_volumetype` string,
  `pricing_publicondemandcost` string,
  `pricing_publicondemandrate` string,
  `pricing_term` string,
  `pricing_unit` string,
  `reservation_normalizedunitsperreservation` string,
  `reservation_totalreservednormalizedunits` string,
  `reservation_totalreservedunits` string,
  `reservation_unitsperreservation` string,
  `resourcetags_aws_createdby` string
)


ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   'separatorChar' = ',',
   'quoteChar' = '\"',
   'escapeChar' = '\\'
)
STORED AS TEXTFILE
LOCATION 's3://{bucket}/{prefix}';
