import os

#_/_/_/ CONFIG - START _/_/_/
ATHENA_BASE_OUTPUT_S3_BUCKET = os.environ.get('ATHENA_BASE_OUTPUT_S3_BUCKET','')
CUR_PROCESSOR_DEST_S3_BUCKET=os.environ.get('CUR_PROCESSOR_DEST_S3_BUCKET','')
CUR_PROCESSOR_DEST_S3_PREFIX=os.environ.get('CUR_PROCESSOR_DEST_S3_PREFIX','')

AWS_ACCOUNT_METADATA_DDB_TABLE = os.environ.get('AWS_ACCOUNT_METADATA_DDB_TABLE','')
STEP_FUNCTION_PREPARE_CUR_ATHENA =  os.environ.get('STEP_FUNCTION_PREPARE_CUR_ATHENA','')
SNS_TOPIC = os.environ.get('SNS_TOPIC','')

AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'us-east-1')

LAMBDA_OWNER_AWS_ACCESS_KEY_ID_VAR_KEY = 'LAMBDA_OWNER_AWS_ACCESS_KEY_ID'
LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY_VAR_KEY = 'LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY'

#_/_/_/ CONFIG - END _/_/_/


ATHENA = 'athena'
QUICKSIGHT = 'quicksight'


ACTION_PREPARE_ATHENA = 'prepare-athena'
ACTION_PREPARE_QUICKSIGHT = 'prepare-quicksight'
ACTION_CREATE_MANIFEST = 'create-manifest'
ACTION_TEST_ROLE = 'test-role'
MANIFEST_TYPE_REDSHIFT = 'redshift'
MANIFEST_TYPE_QUICKSIGHT = 'quicksight'



ACTION_GET_TOTAL_COST = 'get_total_cost'
ACTION_GET_HOURLY_COST = 'get_hourly_cost'
ACTION_GET_COST_BY_SERVICE = 'get_cost_by_service'
ACTION_GET_COST_BY_USAGE_TYPE = 'get_cost_by_usage_type'
ACTION_GET_COST_BY_RESOURCE = 'get_cost_by_resource'
ACTION_GET_USAGE_BY_RESOURCE_ID = 'get_usage_by_resource_id'
ACTION_GET_ACTIVE_RESOURCES = 'get_active_resources'
ACTION_GET_RESOURCE_BY_SERVICE = 'get_resources_by_service'


QUERY_ID_CREATE_DATABASE = 'create_database'
QUERY_ID_CREATE_TABLE = 'create_table'
QUERY_ID_DROP_TABLE = 'drop_table'


ATHENA_QUERY_STATE_SUCCEEDED = 'SUCCEEDED'
ATHENA_QUERY_STATE_FAILED = 'FAILED'
ATHENA_QUERY_STATE_CANCELLED = 'CANCELLED'
ATHENA_QUERY_STATE_CACHED = 'CACHED'



DATA_COLLECTION_STATUS_ACTIVE = 'ACTIVE'
DATA_COLLECTION_STATUS_PAUSED = 'PAUSED'

LAST_PROCESS_STATUS_SUCCEEDED = 'SUCCEEDED'
LAST_PROCESS_STATUS_FAILED = 'FAILED'

VALID_ACTIONS = [ACTION_PREPARE_ATHENA,ACTION_PREPARE_QUICKSIGHT, ACTION_CREATE_MANIFEST, ACTION_TEST_ROLE]

TIMESTAMP_FORMAT = '%Y-%m-%dT%H:%M:%S.%f%Z'
EPOCH_TS = '1970-01-01T00:00:00.000000UTC'











